image: ruby:2.5

cache:
  paths:
  - vendor/

before_script:
  - bundle install --deployment

pages:
  stage: deploy
  script:
  - bundle exec jekyll build --strict-front-matter
  only:
  - gh-pages

test:
  stage: test
  script:
  - bundle exec jekyll build --drafts --strict-front-matter
  except:
  - gh-pages
